[package]
name = "rust-raylib-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rust_raylib_sys"
path = "src/lib.rs"

[dependencies]
libc = "^0.2"

[build-dependencies]
cmake = "0.1"